version: '3.9'
 
services:
  database:
    image: mysql:8
    container_name: carSharingNowDB
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cSnDB
      MYSQL_USER: dave
      MYSQL_PASSWORD: keks
    ports:
      - 3306:3306
    volumes:
     - dockerCSNDatabaseVolume:/var/lib/mysql
    networks:
    - cSnNetwork
      
  springapi:
    image: openjdk
    container_name: carSharingNowSys
    ports:
      - 8443:8080
    depends_on:
      - database
    volumes:
      - ./target/carSharingNow-0.0.1-SNAPSHOT.jar:/app.jar
    command: ["java", "-jar", "app.jar"]    
    networks:
    - cSnNetwork
 
volumes:
  dockerCSNDatabaseVolume:   
  
networks:
  cSnNetwork:
    